name: pokedex
description: "Pokemon Pokedex Unova UI"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # --- Dependencias de Internacionalización (Actualizadas) ---
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2  # Actualizado para coincidir con tu versión de Flutter SDK
  # ---------------------------------------------------------

  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.3
  go_router: ^16.3.0
  graphql_flutter: ^5.2.1
  flutter_dotenv: ^6.0.0
  http: ^1.5.0
  shimmer: ^3.0.0
  equatable: ^2.0.7
  audioplayers: ^6.5.0
  shared_preferences: ^2.3.3
  # Dependencia necesaria para la base de datos local (Favoritos)
  hive_flutter: ^1.1.0
  # Dependencias para compartir
  path_provider: ^2.1.1
  share_plus: ^10.0.0
  # Caché de imágenes para Trivia
  cached_network_image: ^3.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/images/
    - assets/audio/
    - assets/maps/
    - assets/maps/images/
    - .env
